# This is not intended to be a production-ready deployment; It is only intended to demonstrate
# how Catalyst may be deployed in a container environment.
# Carefully read and understand the entire configuration before using any part of it.
# By using this file, you are indicating your acceptance of the Minecraft EULA (https://www.minecraft.net/en-us/eula).
version: "3.8"

services:
  db:
    image: postgres:15.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: catalyst_docker_compose
      POSTGRES_USER: catalyst_docker_compose
      POSTGRES_PASSWORD: catalyst_docker_compose
    volumes:
      - ./db:/var/lib/postgresql/data

  pg-admin:
    image: dpage/pgadmin4:8.0
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: catalyst@example.com
      PGADMIN_DEFAULT_PASSWORD: catalyst

  lp:
    image: ghcr.io/luckperms/luckperms:v5.4.108
    environment:
      LUCKPERMS_STORAGE_METHOD: postgresql
      LUCKPERMS_DATA_ADDRESS: db
      # Use a different database and credentials in production
      LUCKPERMS_DATA_DATABASE: catalyst_docker_compose
      LUCKPERMS_DATA_USERNAME: catalyst_docker_compose
      LUCKPERMS_DATA_PASSWORD: catalyst_docker_compose

  proxy:
    image: itzg/bungeecord:java17
    ports:
      - "25565:25565"
    environment:
      TYPE: VELOCITY
      VELOCITY_VERSION: 3.2.0-SNAPSHOT
      VELOCITY_BUILD_ID: 294
      PLUGINS: |
        https://download.luckperms.net/1521/velocity/LuckPerms-Velocity-5.4.108.jar
        https://cdn.modrinth.com/data/7IbzD4Zm/versions/XDSKb8fH/SignedVelocity-Proxy-1.2.1.jar
      PATCH_DEFINITIONS: /server/velocity-patch-set.json # Does not work yet
      CATALYST_DB_URL: jdbc:postgresql://db:5432/catalyst_docker_compose
      CATALYST_DB_USER: catalyst_docker_compose
      CATALYST_DB_PASSWORD: catalyst_docker_compose
      CATALYST_DISCORD_ENABLED: false
      CATALYST_DISCORD_BOT_TOKEN: "<token here>"
      CATALYST_CHAT_CHANNELS: |
        {
          "global": {
              "id": "global",
              "name": "<green>[Global]",
              "nameFormat": "<gold>[%backend.name%]</gold>%prefix% %displayname%",
              "contentFormat": "%content%",
              "messageFormat": "%channel.name% %name%: %content%",
              "alwaysVisible": true,
              "passthrough": false,
              "discordChannelId": "123456789"
          },
          "admin": {
              "id": "admin",
              "name": "Admin",
              "nameFormat": "<gold>[%backend.name%]</gold>%prefix% %displayname%",
              "contentFormat": "%content%",
              "messageFormat": "<red>%channel.name%%name%: %content%",
              "alwaysVisible": true,
              "passthrough": false,
              "discordChannelId": "123456789"
          }
        }
    volumes:
      - ../../build/libs:/plugins
      - ../config/velocity.toml:/server/velocity.toml
      - ../config/forwarding.secret:/server/forwarding.secret
      - ../config/velocity-patch-set.json:/server/velocity-patch-set.json
      - ./proxy/plugins:/server/plugins

  paper-0:
    image: itzg/minecraft-server:2023.11.1-java21
    expose:
      - 25565
    environment:
      TYPE: PAPER
      VERSION: "1.20.2"
      EULA: true # By using this environment variable, you are indicating your acceptance of the Minecraft EULA
      ONLINE_MODE: false
      PATCH_DEFINITIONS: /config/paper-patch-set.json
      PLUGINS: |
        https://cdn.modrinth.com/data/7IbzD4Zm/versions/tgeLnuE7/SignedVelocity-Paper-1.2.1.jar
    volumes:
      - ./paper-0:/data
      - ../config/paper-patch-set.json:/config/paper-patch-set.json:ro

  paper-1:
    image: itzg/minecraft-server:2023.11.1-java21
    expose:
      - 25565
    environment:
      TYPE: PAPER
      VERSION: "1.20.2"
      EULA: true # By using this environment variable, you are indicating your acceptance of the Minecraft EULA
      ONLINE_MODE: false
      PATCH_DEFINITIONS: /config/paper-patch-set.json
      PLUGINS: |
        https://cdn.modrinth.com/data/7IbzD4Zm/versions/tgeLnuE7/SignedVelocity-Paper-1.2.1.jar
    volumes:
      - ./paper-1:/data
      - ../config/paper-patch-set.json:/config/paper-patch-set.json:ro
